<?php
/**
 * Single template for markil_module post type.
 *
 * Loaded automatically by the plugin's template_include filter when
 * visiting /markil-module/{slug}/ — produces a full WooCommerce-style
 * detail page (header + full-detail layout + footer) that scrolls
 * naturally and works in any theme.
 *
 * Do NOT edit this file directly — override it from your theme by copying
 * to: yourtheme/markil-modules/single-markil_module.php
 */
if ( ! defined( 'ABSPATH' ) ) exit;

get_header();

?>
<div class="markil-single-wrap">
<?php
if ( have_posts() ) :
    while ( have_posts() ) : the_post();
        $post_id = get_the_ID();

        // Build module data via Ajax::format_module() (full mode)
        if ( ! class_exists( '\Markil\Ajax' ) ) {
            require_once MARKIL_PATH . 'includes/class-markil-ajax.php';
        }
        $markil_ajax = new \Markil\Ajax();
        $m = $markil_ajax->format_module( $post_id, true );

        $currency = get_option( 'markil_currency', 'تومان' );

        // Allow theme/site to override settings via filter
        $settings = apply_filters( 'markil_single_settings', [
            'show_breadcrumbs'     => 'yes',
            'show_sidebar'         => 'yes',
            'show_features_bar'    => 'yes',
            'show_sidebar_feats'   => 'yes',
            'show_detail_sections' => 'yes',
            'show_guarantee'       => 'yes',
            'show_video'           => 'yes',
            'sidebar_position'     => 'left',
            'breadcrumb_home'      => __( 'خانه', 'markil-modules' ),
        ], $post_id, $m );

        include MARKIL_PATH . 'templates/full-detail-layout.php';

    endwhile;
endif;
?>
</div>
<?php
get_footer();
